name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/rafaelnsantos/devcontainer-latex:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        env:
          GIT_SSL_NO_VERIFY: true

      - name: Compile LaTeX document
        run: |
          pdflatex -synctex=1 -interaction=nonstopmode -file-line-error -shell-escape main.tex
          bibtex main
          pdflatex -synctex=1 -interaction=nonstopmode -file-line-error -shell-escape main.tex
          pdflatex -synctex=1 -interaction=nonstopmode -file-line-error -shell-escape main.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: main.pdf
          path: main.pdf

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download PDF artifact
        uses: actions/download-artifact@v4
        with:
          name: main.pdf
          path: .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload PDF to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./main.pdf
          asset_name: main.pdf
          asset_content_type: application/pdf