name: Publish Devcontainer Image
on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Docker build platform (ex: linux/amd64,linux/arm64)'
        required: false
        default: 'linux/amd64'
        options:
          - linux/amd64
          - linux/arm64
          - linux/amd64,linux/arm64
      ubuntu_version:
        description: 'Ubuntu version (ex: 22.04, 24.04)'
        required: false
        default: '22.04'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  id-token: write
  contents: read
  attestations: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ github.event.inputs.platform }}-ubuntu${{ github.event.inputs.ubuntu_version }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: ${{ github.event.inputs.platform }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            UBUNTU_VERSION=${{ github.event.inputs.ubuntu_version }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
